name: CMake Build Matrix

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: gcc
        include:
          - os: windows-latest
            compiler: msvc
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ env.BUILD_TYPE }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Doxygen
        shell: cmake -P {0}
        run: |
          if ("${{ runner.os }}" STREQUAL "Windows")
            execute_process(COMMAND echo No dependencies to install.)
          elseif ("${{ runner.os }}" STREQUAL "Linux")
            execute_process(COMMAND sudo apt-get install -y doxygen)
          elseif ("${{ runner.os }}" STREQUAL "macOS")
            execute_process(COMMAND brew install doxygen)
          endif()
          
      - name: Install Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
        
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}